### ISSUE TITLE
Integrate with code search

### ISSUE THREAD

**Issue by djsegal** [JuliaPackaging/cloneallpackages#3]
I feel like you're pretty close to having an efficient code searcher.

Have you thought about adding google's [codesearch](https://github.com/google/codesearch)?

**Comment by tkelman** [comment]
I've been fine with using grep or other variants for now. I don't usually have a go toolchain, or particularly feel like setting one up, on most systems I work on.

**Comment by djsegal** [comment]
Fair enough. When grep gets too slow, at least this was suggested. Closing.
